sudo: required
services:
    - docker
before_install:
    - docker build -t test/test -f Dockerfile.dev .
script:
    - docker run -e CI=true test/test npm run test -- --coverage
deploy:
    edge: true
    provider: "elasticbeanstalk"
    region: "ap-southeast-1"
    app: "react-test"
    env: "ReactTest-env"
    bucket-name: "elasticbeanstalk-ap-southeast-1-718737905471"
    bucket-path: "react-test"
    on:
        branch: "master"
    access_key_id: "$AWS_ACCESS_KEY"
    secret_access_key: "$AWS_SECRET_KEY"